apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  labels:
    app: hello-k8s
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-k8s
    tier: hello-k8s
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-k8s
  labels:
    app: hello-k8s
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-k8s
        tier: hello-k8s
    spec:
      containers:
      - image: 10.0.1.4:5000/hello-k8s:latest
        name: hello-k8s
        ports:
        - containerPort: 80
          name: hello-k8s