apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-k8s
spec:
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
  selector:
    app: hello-k8s
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    app: hello-k8s
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-k8s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - image: 10.0.1.4:5000/hello-k8s:edge
        name: hello-k8s
        ports:
        - containerPort: 80